services:

    _defaults:
        autowire: true
        autoconfigure: true

    keiwen_cacofony.request:
        class: Symfony\Component\HttpFoundation\RequestStack
        factory:
            - '@request_stack'
            - 'getCurrentRequest'

    Keiwen\Cacofony\EventListener\ParamFetcherListener:
        arguments:
            $fetcherClass: '%keiwen_cacofony.param_fetcher.fetcher_class%'
            $readerClass: '%keiwen_cacofony.param_fetcher.reader_class%'
            $controllerParam: '%keiwen_cacofony.param_fetcher.controller_parameter%'

    Keiwen\Cacofony\Association\NelmioApiDoc\KeiwenCacofonyHandler:
        tags:
            - { name: nelmio_api_doc.extractor.handler }
