
parameters:
    keiwen_cacofony.param_fetcher_listener.class: Keiwen\Cacofony\EventListener\ParamFetcherListener
    keiwen_cacofony.param_fetcher.class: Keiwen\Cacofony\ParamFetcher\ParamFetcher
    keiwen_cacofony.param_reader.class: Keiwen\Cacofony\ParamFetcher\ParamReader
    keiwen_cacofony.nelmioapidoc.handler.class: Keiwen\Cacofony\Association\NelmioApiDoc\KeiwenCacofonyHandler

services:

    keiwen_cacofony.request:
        class: Symfony\Component\HttpFoundation\RequestStack
        factory:
            - '@request_stack'
            - 'getCurrentRequest'


    keiwen_cacofony.param_fetcher_listener:
        class: '%keiwen_cacofony.param_fetcher_listener.class%'
        arguments: ['@service_container', '@annotation_reader', '@validator']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: '%keiwen_cacofony.param_fetcher_listener.priority%' }


    keiwen_cacofony.nelmioapidoc.extractor.handler:
        class: '%keiwen_cacofony.nelmioapidoc.handler.class%'
        tags:
            - { name: nelmio_api_doc.extractor.handler }
