
services:
    Keiwen\Cacofony\EventListener\:
        resource: '../../EventListener'


    Keiwen\Cacofony\Security\RoleChecker:
        arguments:
            $authorizationChecker: '@security.authorization_checker'
            $rolePrefixes: '%keiwen_cacofony.rolechecker.role_prefixes%'
