
services:
    keiwen_cacofony.twig.string:
        class: Keiwen\Cacofony\Twig\TwigString
        tags:
            - { name: twig.extension }
            
    keiwen_cacofony.twig.intl:
        class: Keiwen\Cacofony\Twig\TwigIntl
        tags:
            - { name: twig.extension }

