

services:

    keiwen_cacofony.autodump:
        class: Keiwen\Cacofony\EventListener\AutoDumpListener
        arguments: ['%keiwen_cacofony.autodump.paramname%', '@?twig']
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 20 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 20 }

    keiwen_cacofony.templateParam:
        class: Keiwen\Cacofony\EventListener\TemplateParamListener
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 30 }

    keiwen_cacofony.localeListener:
        class: Keiwen\Cacofony\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    keiwen_cacofony.okresponsecode:
        class: Keiwen\Cacofony\EventListener\OkResponseCodeListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -10 }

