services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #EVENT LISTENER
    Keiwen\Cacofony\EventListener\:
        resource: '../../EventListener'

    Keiwen\Cacofony\EventListener\AutoDumpListener:
        arguments:
            $appEnv: '%kernel.environment%'
            $parameterName: '%keiwen_cacofony.autodump.paramname%'
        public: true

    Keiwen\Cacofony\EventListener\ParamFetcherListener:
        arguments:
            $fetcherClass: '%keiwen_cacofony.param_fetcher.fetcher_class%'
            $readerClass: '%keiwen_cacofony.param_fetcher.reader_class%'
            $controllerParam: '%keiwen_cacofony.param_fetcher.controller_parameter%'


    #REQUEST
    Keiwen\Cacofony\Http\Request:
        class: Symfony\Component\HttpFoundation\RequestStack
        factory:
            - '@request_stack'
            - 'getCurrentRequest'
        public: true

    #ASSOCIATION
    Keiwen\Cacofony\Association\NelmioApiDoc\KeiwenCacofonyHandler:
        tags:
            - { name: nelmio_api_doc.extractor.handler }

    #ROLE CHECKER
    Keiwen\Cacofony\Security\RoleChecker:
        arguments:
            $rolePrefixes: '%keiwen_cacofony.rolechecker.role_prefixes%'

    #ENTITIES
    Keiwen\Cacofony\EntitiesManagement\EntityRegistry:
        arguments:
            $managerRegistry: '@?doctrine'
        public: true
    Keiwen\Cacofony\EntitiesManagement\Assimilator:
        arguments:
            $entityRegistry: '%keiwen_cacofony.default_entity_registry%'

    #TWIG
    Keiwen\Cacofony\Twig\:
        resource: '../../Twig'

    Keiwen\Cacofony\Twig\TwigRequest:
        arguments:
            $request: '@Keiwen\Cacofony\Http\Request'

    #TEMPLATING
    sensio_framework_extra.view.guesser:
        class: Keiwen\Cacofony\Templating\TemplateGuesser



