services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #EVENT LISTENER
    Keiwen\Cacofony\EventListener\:
        resource: '../../EventListener'

    Keiwen\Cacofony\EventListener\AutoDumpListener:
        arguments:
            $appEnv: '%kernel.environment%'
            $parameterName: '%keiwen_cacofony.autodump.paramname%'
        public: true


    #REQUEST
    Keiwen\Cacofony\Http\Request:
        class: Symfony\Component\HttpFoundation\RequestStack
        factory:
            - '@request_stack'
            - 'getCurrentRequest'
        public: true

    #ROLE CHECKER
    Keiwen\Cacofony\Security\RoleChecker:
        arguments:
            $rolePrefixes: '%keiwen_cacofony.rolechecker.role_prefixes%'

    #TOKEN GENERATOR
    Keiwen\Cacofony\Security\TokenGenerator:
        arguments:
            $secret: '%keiwen_cacofony.token_generator.secret%'
            $cipherAlgo: '%keiwen_cacofony.token_generator.cipher_algo%'
            $opensslIV: '%keiwen_cacofony.token_generator.openssl_iv%'

    #ENTITIES
    Keiwen\Cacofony\EntitiesManagement\EntityRegistry:
        arguments:
            $managerRegistry: '@?doctrine'
        public: true
    Keiwen\Cacofony\EntitiesManagement\Assimilator:
        arguments:
            $entityRegistry: '%keiwen_cacofony.default_entity_registry%'

    #TWIG
    Keiwen\Cacofony\Twig\:
        resource: '../../Twig'

    Keiwen\Cacofony\Twig\TwigRequest:
        arguments:
            $request: '@Keiwen\Cacofony\Http\Request'

    #TEMPLATING
    sensio_framework_extra.view.guesser:
        class: Keiwen\Cacofony\Templating\TemplateGuesser



