

services:
    twig.extension.trans:
        class: Keiwen\Cacofony\Twig\TwigTranslation
        arguments: ['@translator']
        tags:
            - { name: twig.extension }

    keiwen_cacofony.twig.string:
        class: Keiwen\Cacofony\Twig\TwigString
        tags:
            - { name: twig.extension }
            
    keiwen_cacofony.twig.intl:
        class: Keiwen\Cacofony\Twig\TwigIntl
        tags:
            - { name: twig.extension }
            
    keiwen_cacofony.twig.security:
        class: Keiwen\Cacofony\Twig\TwigSecurity
        arguments: ['@keiwen_cacofony.rolechecker']
        tags:
            - { name: twig.extension }

