

services:

    _defaults:
        autowire: true
        autoconfigure: true

    Keiwen\Cacofony\Twig\:
        resource: '../../Twig'

    Keiwen\Cacofony\Twig\TwigRequest:
        arguments:
            $request: '@keiwen_cacofony.request'

