

services:

    keiwen_cacofony.twig_request:
        class: Keiwen\Cacofony\Twig\TwigRequest
        public: false
        arguments: ['@keiwen_cacofony.request']
        tags:
            - { name: twig.extension }

    twig.extension.trans:
        class: Keiwen\Cacofony\Twig\TwigTranslation
        arguments: ['@translator', '@?twig', '@?session']
        tags:
            - { name: twig.extension }

    keiwen_cacofony.twig.string:
        class: Keiwen\Cacofony\Twig\TwigString
        tags:
            - { name: twig.extension }
            
    keiwen_cacofony.twig.intl:
        class: Keiwen\Cacofony\Twig\TwigIntl
        tags:
            - { name: twig.extension }
            
    keiwen_cacofony.twig.security:
        class: Keiwen\Cacofony\Twig\TwigSecurity
        arguments: ['@keiwen_cacofony.rolechecker']
        tags:
            - { name: twig.extension }

