

services:

    keiwen_cacofony.app_controller:
        class: Keiwen\Cacofony\Controller\AppController

    keiwen_cacofony.api_controller:
        class: Keiwen\Cacofony\Controller\ApiController


    keiwen_cacofony.twig_controller:
        class: Keiwen\Cacofony\Twig\TwigController
        public: false
        arguments: ['@keiwen_cacofony.app_controller']
        tags:
            - { name: twig.extension }
