services:

    _defaults:
        autowire: true
        autoconfigure: true

    Keiwen\Cacofony\EventListener\:
        resource: '../../EventListener'

    Keiwen\Cacofony\EventListener\AutoDumpListener:
        arguments:
            $parameterName: '%keiwen_cacofony.autodump.paramname%'

    Keiwen\Cacofony\EventListener\LocaleListener:
        arguments:
            $defaultLocale: '%kernel.default_locale%'

    Keiwen\Cacofony\Controller\ExceptionController:

    Keiwen\Cacofony\Controller\ExceptionController:
        arguments:
            $debug: '%kernel.debug%'
            $previousOnTwigError: '%keiwen_cacofony.exception.previous_on_twigerror%'


