keiwen_cacofony:
    param_fetcher:
        controller_parameter: paramFetcher
        fetcher_class:        Keiwen\Cacofony\ParamFetcher\ParamFetcher
        reader_class:         Keiwen\Cacofony\ParamFetcher\ParamReader
    controller:
        default_cache:        cache
        default_entity_registry: Keiwen\Cacofony\EntitiesManagement\EntityRegistry
        default_request:      '@Keiwen\Cacofony\Http\Request'
        getparam_disable_cache: noCache
        api_format_response:  true
    autodump:
        # Name of the dump's key containing template parameters
        parameter_name:       _templatesParameters
    exception:
        previous_on_twigerror: true
    rolechecker:
        role_prefixes:        []
    token_generator:
        secret:               Keiwen_Cacofony_Secret_To_Be_Changed
        # see openSSL allowed algo
        cipher_algo:          aes-128-cbc
        # have to be exactly 16-chars long
        openssl_iv:           CACO_init_osslIV
    code_translator:
        locale:               transCode
        display_pattern:      '#{domain}[{message}]'
    template_guesser:
        extension:            html.twig
