
parameters:
    keiwen_cacofony_widget.bundlename: 'KeiwenCacofonyWidgetBundle'

services:

    keiwen_cacofony_widget.controller:
        class: Keiwen\Cacofony\WidgetBundle\Controller\WidgetController
        arguments:
            - '@service_container'

    keiwen_cacofony_widget.twig:
        class: Keiwen\Cacofony\WidgetBundle\Twig\TwigWidget
        arguments:
            - '@keiwen_cacofony_widget.controller'
            - '%keiwen_cacofony_widget.bundlename%'
        tags:
            - { name: twig.extension }

    keiwen_cacofony_widget.async_launcher:
        class: Keiwen\Cacofony\WidgetBundle\EventListener\AsyncWidgetListener
        arguments:
            - '@keiwen_cacofony_widget.controller'
            - '@twig'
        tags:
            - { name: kernel.event_subscriber }

