
parameters:
    keiwen_cacofony_widget.bundleclassname: 'Keiwen\Cacofony\WidgetBundle\KeiwenCacofonyWidgetBundle'

services:


    keiwen_cacofony_widget.twig:
        class: Keiwen\Cacofony\WidgetBundle\Twig\TwigWidget
        arguments:
            - '@service_container'
            - '%keiwen_cacofony_widget.bundleclassname%'
        tags:
            - { name: twig.extension }

    keiwen_cacofony_widget.async_launcher:
        class: Keiwen\Cacofony\WidgetBundle\EventListener\AsyncWidgetListener
        arguments:
            - '@twig'
        tags:
            - { name: kernel.event_subscriber }
